name: PR Check
on:
  pull_request:
    branches:
      - main
jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        working-directory: ./src
        run: npm ci
  build-dockercompose:
    runs-on: ubuntu-latest
    needs: check-dependencies
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Compose
        run: docker-compose -f docker-compose.example.yaml build
